#=================
# COLORS
#=================

ESC_SEQ="\x1b["
COL_RESET=$ESC_SEQ"39;49;00m"
COL_RED=$ESC_SEQ"31;05m"
COL_GREEN=$ESC_SEQ"32;055555m"
COL_GREEN_ITALIC=$ESC_SEQ"32;03m"
COL_YELLOW=$ESC_SEQ"33;05m"
COL_BLUE=$ESC_SEQ"34;05m"
COL_MAGENTA=$ESC_SEQ"35;05m"
COL_CYAN=$ESC_SEQ"36;05m"
COL_NORMAL_ITALIC=$ESC_SEQ"39;03m"

#make ls respect solarized dircolors
#dircolors .dircolors 2>&1 /dev/null


#=================
# GREETING MESSAGE
#=================

echo -e "$COL_GREEN_ITALIC"" Good luck and have fun!" "$COL_RESET"
#echo -e "$COL_BLUE""    You are using zsh." "$COL_RESET" 
echo "$COL_NORMAL_ITALIC"" type 'showvars', 'showaliases' and 'showfuncs' to see variables,"
echo " aliases and functions defined in the ~/.zshrc file.""$COL_RESET" 




#=================
# ZBOX-STUFF
#=================


#AUTOMATICALLY LOADING MODULES IF ON ZBOX: hostname=f1

if [[ "$HOSTNAME" == 'f1' ]]; then
    #enter here modules to be loaded/removed
    module rm gcc
    module switch mpi mpi/intel/5.0.3.048
    module switch intel/2013 intel/2015
    echo -e "$COL_GREEN" "Modules configured according to ~/.zshrc file" "$COL_RESET"
fi




#IF ON ZBOX: ADD SELF MADE PROGRAMS TO PATH

if [[ "$HOSTNAME" == 'f1' || "$HOSTNAME" == "malin1" ]]; then
    #ramses stuff
    PATH="/zbox/user/mivkov/source/executables:"$PATH
    PATH="/zbox/user/mivkov/source/executables/ramses/hop:"$PATH
    PATH="/zbox/user/mivkov/source/executables/ramses:"$PATH
    PATH="/zbox/user/mivkov/source/executables/selfmade:"$PATH
    PATH="/zbox/user/mivkov/source/executables/dice/bin:"$PATH #dice
    #Hydro stuff
    PATH="/zbox/user/mivkov/hydro/scripts:"$PATH
    PATH="/zbox/user/mivkov/hydro/scripts/scaling:"$PATH
fi

PATH="/home/uzh/mivkov/programme/bin:"$PATH # vim, ffmpeg
PATH="/home/uzh/mivkov/programme/include:"$PATH
PATH="/home/uzh/mivkov/programme/lib:"$PATH
PATH="/home/uzh/mivkov/programme/share/ffmpeg:"$PATH

# for ffmpeg to work
export LD_LIBRARY_PATH="/home/uzh/mivkov/programme/lib:"LD_LIBRARY_PATH



#CHECKING IF I'M ON ZBOX BEFORE EXECUTING SBATCH OR SQUEUE, ALSO SQUEUE ALIAS

function mbatch { # function to check first if I'm on zbox before executing sbatch. Also copy sbatch output to sbatch_jobID.log
    if [[ "$HOSTNAME" == 'f1' ]]; then
        export EXECDATE=`date +%F_%Hh%M`
        sbatch $1 | tee "sbatch_jobID_$EXECDATE.log"
    else
        echo -e "$COL_RED" "You are not on zbox..." "$COL_RESET"
    fi
}



function sq { # function to check first if I'm on zbox before execution squeue -u mivkov
    if [[ "$HOSTNAME" == 'f1' ]]; then
        squeue -u mivkov    
    else
        echo -e "$COL_RED" "You are not on zbox..." "$COL_RESET"
    fi
}

function rgrep {
    grep -i -r $1 . | grep -v "utils" | grep -v "Binary" | grep -v "patch"
    }











#=================
#PERSONAL ALIASES
#=================

alias ..='cd ..'
alias ll='ls -lh'
alias la='ls -a'

#self-installed programs
alias vim='/home/uzh/mivkov/programme/bin/vim'
alias ffmpeg='/home/uzh/mivkov/programme/bin/ffmpeg'


# RAMSES STUFF
# ------------
alias zbox='ssh -2Y -i ~/.ssh/forzbox zbox'
alias ramses='cd /home/uzh/mivkov/bachelorarbeit/ramses/'
alias rexec='cd /zbox/user/mivkov/ramses-exec/'
alias icfiles='cd /zbox/user/mivkov/ic_files/'
alias go='sbatch job-unbinding.slm'

#go to clumpfinder dir
alias unb='cd /zbox/user/mivkov/ramses-exec/unbinding'
alias p='cd /zbox/user/mivkov/ramses-exec/pawel'
alias clmp=unb
alias clump=clmp
alias d='cd /zbox/user/mivkov/ramses-exec/dice'

#go to ramses bin dir to make
alias mk='cd /home/uzh/mivkov/bachelorarbeit/ramses/trunk/ramses/bin_clean/'
alias mkd='cd /home/uzh/mivkov/bachelorarbeit/ramses/trunk/ramses/bin_dice/'
alias comp=mk

# go to main dir
alias src='cd /home/uzh/mivkov/bachelorarbeit/ramses/trunk/ramses/'

#go to my patch dir
alias pa='cd /home/uzh/mivkov/bachelorarbeit/ramses/trunk/ramses/patch/unbinding'

alias scr='cd /zbox/user/mivkov/source/executables/selfmade'




#remove logfiles from a zbox run
alias rmlog="(rm -f run*.log) 2>/dev/null; (rm -f sbatch*.log) 2>/dev/null; (rm -f slurm*.out) 2>/dev/null"

#remove output_00009 dir 
alias rm9='rm -r output_00009/'

#copy ramses exec to my testing directory
alias cpr='cp /home/uzh/mivkov/bachelorarbeit/ramses/trunk/ramses/bin/ramses3d-mladen /zbox/user/mivkov/ramses-exec/unbinding'
alias cpd='cp /home/uzh/mivkov/bachelorarbeit/ramses/trunk/ramses/bin/ramses3d-dice /zbox/user/mivkov/ramses-exec/dice'

#----------------------

# HYDRO STUFF
alias hy='cd /zbox/user/mivkov/hydro'
alias hs='cd /zbox/user/mivkov/hydro/HYDRO/F90/MPI/Src'
alias he='cd /zbox/user/mivkov/hydro/HYDRO/F90/MPI/exec/parallel_code/'
#alias cph='cp /zbox/user/mivkov/hydro/HYDRO/F90/MPI/Src/hydro_mpi /zbox/user/mivkov/hydro/HYDRO/F90/MPI/exec/parallel_code/'
#export HEX='/zbox/user/mivkov/hydro/HYDRO/F90/MPI/exec/'
#alias goh='sbatch job-hydro.slm'
#
#alias sc='cd /zbox/user/mivkov/hydro/HYDRO/F90/Scalingtests/Src '
#alias se='cd /zbox/user/mivkov/hydro/HYDRO/F90/Scalingtests/exec ' 

#==================
#PERSONAL VARIABLES
#==================


export PATCH=/home/uzh/mivkov/bachelorarbeit/ramses/patches_mladen
export EXEC=/home/uzh/mivkov/bachelorarbeit/ramses/execution
export SRC='/zbox/user/mivkov/source'
export SCR='/zbox/user/mivkov/source/executables/selfmade'

# prompt
export NEWLINE=$'\n'
export PROMPT="%F{blue} [%n@%m] @ %d %f ${NEWLINE}    "


#functions to show specified content of ~/.SHELLrc file

export shellfile_in_use=$HOME/.zshrc




#==================
#PERSONAL FUNCTIONS
#==================

#=================
# show zshrc data
function showaliases { #function to print all my self defined aliases in the ~/.zshrc file.
    echo " "
    echo "Printing all aliases defined in the "$shellfile_in_use" file:"
    echo " "
    sed -e 's/^\s*//' -e '/^$/d' "$shellfile_in_use" | egrep --color=always '^[[:blank:]]*alias'
    echo " "
}

function showvars { #function to print all my self defined and exported variables in the ~/.zshrc file.
    echo " "
    echo "Printing all exported variables defined in the "$shellfile_in_use" file:"
    echo " "
    sed -e 's/^\s*//' -e '/^$/d' "$shellfile_in_use" | egrep --color=always '^[[:blank:]]*export'
    echo " "
}


function showfuncs { #function to print all my self defined functions in the ~/.zshrc file.
    echo " "
    echo "Printing all functions defined in the "$shellfile_in_use" file:"
    echo " "
    sed -e 's/^\s*//' -e '/^$/d' $shellfile_in_use | egrep --color=always '^[[:blank:]]*function'
    echo " "
}

#============

function rmphew { # remove clumpfinder output. default in output_00008, else use rmphew <number>
    if [[ "$#" == 0 ]] then
        cd output_00008 2> /dev/null
        rm clump_* 2> /dev/null
        rm halo_* 2> /dev/null
        cd ..
    else
        cd output_0000$1
        rm clump_*
        rm halo_*
        cd ..
    fi
}

function rma { #remove phew output in output_00008, directory output_0009 and sbatch/slurm log files from directory.
    rmphew 2> /dev/null
    rm9 2> /dev/null
    rmlog 2> /dev/null
    rm output_00008/mladen_* 2> /dev/null
}
