#!/bin/bash
# compiles a given .c file for openMP.
# also takes filename without .c as argument. Both work.
# ./com some_file.c or ./com some_file both work.
# If compilation was successful, it will be executed.


if [[ $# == 0 ]]; then
    echo "no arguments given. Can't handle that."
    exit
else
    filename=$1;
    exec=${filename%.*c}    #remove suffix, if it exists
    exec=${exec%.}      #remove . if it exists

    filename="$exec".c      #add .c suffix in case it wasn't there
    exec="$exec".exe         #add .exe suffix

    echo -e "\x1b[32;01m" "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" "\x1b[39;49;00m"
    echo -e "\x1b[32;01m" "~~~~ now compiling" "$filename" "~~~""\x1b[39;49;00m"
    echo -e "\x1b[32;01m" "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" "\x1b[39;49;00m"

    echo "    gcc -g -Wall -fopenmp -o " "$exec" "$filename" 

    if gcc -g -Wall -fopenmp -o "$exec" "$filename" ; then
    #if gcc -g -Wall -Werror -fopenmp -o "$exec" "$filename" ; then
        # -Werror: treat warnings ar errors, so don't run the execfile

        echo -e "\x1b[32;01m" "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" "\x1b[39;49;00m"
        echo -e "\x1b[32;01m" "~~~~~~~~~~ PROGRAM STARTING ~~~~~~~~~~~~~~" "\x1b[39;49;00m" 
        echo -e "\x1b[32;01m" "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" "\x1b[39;49;00m" 

        ./"$exec";
    else
        exit;
    fi

fi

exit
