#!/bin/bash
echo "Importing ramses stuff"

export BA=/home/mivkov/UZH/Bachelorarbeit/bachelorarbeit
export RES=/home/mivkov/UZH/Bachelorarbeit/bachelorarbeit/files/results
export REP=/home/mivkov/UZH/Bachelorarbeit/bachelorarbeit/report

# Change dirs
alias ba='cd ~/UZH/Bachelorarbeit/bachelorarbeit'
alias pa='cd ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/patch/unbinding'
alias mk='cd ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_unbinding'
alias mkc='cd ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_clean'
alias mkd='cd ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_dice'
alias mki='cd ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_dice_intel'
alias mkm='cd ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_dice_nompi'
alias scr='cd ~/UZH/Bachelorarbeit/bachelorarbeit/programs/scripts'
alias dic='cd ~/UZH/Bachelorarbeit/bachelorarbeit/files/ic_files/dice/'

#alias mli='cd masspnt/linbins'
#alias mlo='cd masspnt/logbins'
#alias pli='cd poisson/linbins'
#alias plo='cd poisson/logbins'

alias cos='cd ~/UZH/Bachelorarbeit/bachelorarbeit/exec/cosmo'
#alias coo='cd ~/UZH/Bachelorarbeit/bachelorarbeit/exec/cosmo-old'
#alias two='cd ~/UZH/Bachelorarbeit/bachelorarbeit/exec/dice_two'
#alias sub='cd ~/UZH/Bachelorarbeit/bachelorarbeit/exec/dice_substructure'
alias te='cd ~/UZH/Bachelorarbeit/bachelorarbeit/exec/testing'
alias tb='cd ~/UZH/Bachelorarbeit/bachelorarbeit/exec/test_big'

#alias tli='cd ~/UZH/Bachelorarbeit/bachelorarbeit/exec/two_linbins'
#alias tlic='cd ~/UZH/Bachelorarbeit/bachelorarbeit/exec/two_linbins_nocut'
#alias tlo='cd ~/UZH/Bachelorarbeit/bachelorarbeit/exec/two_logbins'
#alias tloc='cd ~/UZH/Bachelorarbeit/bachelorarbeit/exec/two_logbins_nocut'

#alias slo='cd ~/UZH/Bachelorarbeit/bachelorarbeit/exec/sub_logbins'
#alias sloc='cd ~/UZH/Bachelorarbeit/bachelorarbeit/exec/sub_logbins_nocut'

#alias cl='cd ~/UZH/Bachelorarbeit/bachelorarbeit/exec/cosmo_logbins'
#alias clc='cd ~/UZH/Bachelorarbeit/bachelorarbeit/exec/cosmo_logbins_nocut'


# scripts
alias u=unbindingplot
alias pp=plot_particles
alias r=reportplot




#shortcut functions
alias cpr='cp ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_unbinding/ramses3d-mladen ~/UZH/Bachelorarbeit/bachelorarbeit/exec;cp ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_unbinding/ramses3d-mladen ~/UZH/Bachelorarbeit/bachelorarbeit/programs/compiled'

alias cpo='cp ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_unbinding/ramses3d-mladen-old ~/UZH/Bachelorarbeit/bachelorarbeit/exec;cp ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_unbinding/ramses3d-mladen-old ~/UZH/Bachelorarbeit/bachelorarbeit/programs/compiled'

alias cpc='cp ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_clean/ramses3d-clean ~/UZH/Bachelorarbeit/bachelorarbeit/exec;cp ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_clean/ramses3d-clean ~/UZH/Bachelorarbeit/bachelorarbeit/programs/compiled'

alias cpd='cp ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_dice/ramses3d-dice ~/UZH/Bachelorarbeit/bachelorarbeit/exec; cp ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_dice/ramses3d-dice ~/UZH/Bachelorarbeit/bachelorarbeit/programs/compiled'

alias cpdo='cp ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_dice/ramses3d-dice-old ~/UZH/Bachelorarbeit/bachelorarbeit/exec; cp ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_dice/ramses3d-dice-old ~/UZH/Bachelorarbeit/bachelorarbeit/programs/compiled'

alias cpi='cp ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_dice_intel/ramses3d-dice-intel ~/UZH/Bachelorarbeit/bachelorarbeit/exec; cp ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_dice_intel/ramses3d-dice-intel ~/UZH/Bachelorarbeit/bachelorarbeit/programs/compiled'

alias cpm='cp ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_dice_nompi/ramses3d-dice-nompi ~/UZH/Bachelorarbeit/bachelorarbeit/exec; cp ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_dice_nompi/ramses3d-dice-nompi ~/UZH/Bachelorarbeit/bachelorarbeit/programs/compiled'

alias cpmo='cp ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_dice_nompi/ramses3d-dice-nompi-old ~/UZH/Bachelorarbeit/bachelorarbeit/exec; cp ~/UZH/Bachelorarbeit/bachelorarbeit/ramses/trunk/ramses/bin_dice_nompi/ramses3d-dice-nompi-old ~/UZH/Bachelorarbeit/bachelorarbeit/programs/compiled'

alias god='DATE=`date +%F_%Hh%M`; mpiexec -n 4 ../../../ramses3d-dice unbinding-dice.nml 2>"$DATE"_error.log | tee run"$DATE".log'
alias got='DATE=`date +%F_%Hh%M`; mpiexec -n 4 ../ramses3d-dice unbinding-dice.nml 2>"$DATE"_error.log | tee run"$DATE".log'
alias goto='DATE=`date +%F_%Hh%M`; mpiexec -n 4 ../ramses3d-dice-old unbinding-dice.nml 2>"$DATE"_error.log | tee run"$DATE"-old.log'
alias goo='DATE=`date +%F_%Hh%M`; mpiexec -n 4 ../ramses3d-mladen-old unbinding.nml 2>"$DATE"_error.log | tee run"$DATE"-old.log'
alias goc='DATE=`date +%F_%Hh%M`; mpiexec -n 4 ../ramses3d-clean unbinding.nml 2>"$DATE"_error.log | tee run"$DATE".log'
alias go='DATE=`date +%F_%Hh%M`; mpiexec -n 4 ../ramses3d-mladen unbinding.nml 2>"$DATE"_error.log | tee run"$DATE".log'
alias goi='DATE=`date +%F_%Hh%M`; mpiexec -n 4 ../ramses3d-dice-intel unbinding-dice.nml 2>"$DATE"_error-intel.log | tee run"$DATE"-intel.log'
alias gom='DATE=`date +%F_%Hh%M`; ../ramses3d-dice-nompi unbinding-dice.nml 2>"$DATE"_error-nompi.log | tee run"$DATE"-nompi.log'
alias gomo='DATE=`date +%F_%Hh%M`; ../ramses3d-dice-nompi-old unbinding-dice.nml 2>"$DATE"_error-nompi.log | tee run"$DATE"-nompi-old.log'
alias gor='DATE=`date +%F_%Hh%M`; mpiexec -n 4 ../ramses3d-reltest unbinding-dice.nml 2>"$DATE"_error-reltest.log | tee run"$DATE"-reltest.log'

alias rmlog='rm -i *.log'

# PATH
export PATH="/home/mivkov/UZH/Bachelorarbeit/bachelorarbeit/programs/scripts:"$PATH # selfmade python scripts
export SCR=/home/mivkov/UZH/Bachelorarbeit/bachelorarbeit/programs/scripts
export PATH="/home/mivkov/UZH/Bachelorarbeit/bachelorarbeit/programs/compiled/bin:"$PATH
export PATH="/home/mivkov/UZH/Bachelorarbeit/bachelorarbeit/programs/compiled:"$PATH # compiled ramses execs

